name: Teams Notification

on:
  push: {main, dev}
  release: {}


jobs:
  without_optional_params:
    name: Minimal notification
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: nerdherd/notify-microsoft-teams@main
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}

  if_failure:
    name: Only if failure
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: nerdherd/notify-microsoft-teams@main
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
